/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ServicesWiringRewiringRouteImport } from './routes/services/wiring-rewiring'
import { Route as ServicesSecuritySystemsRouteImport } from './routes/services/security-systems'
import { Route as ServicesResidentialHvacRouteImport } from './routes/services/residential-hvac'
import { Route as ServicesResidentialRouteImport } from './routes/services/residential'
import { Route as ServicesPanelUpgradesRouteImport } from './routes/services/panel-upgrades'
import { Route as ServicesIndustrialRouteImport } from './routes/services/industrial'
import { Route as ServicesIndoorAirQualityRouteImport } from './routes/services/indoor-air-quality'
import { Route as ServicesHvacRepairsRouteImport } from './routes/services/hvac-repairs'
import { Route as ServicesHvacMaintenanceRouteImport } from './routes/services/hvac-maintenance'
import { Route as ServicesHvacInstallRouteImport } from './routes/services/hvac-install'
import { Route as ServicesHeatingRouteImport } from './routes/services/heating'
import { Route as ServicesGeneratorRouteImport } from './routes/services/generator'
import { Route as ServicesEvChargerRouteImport } from './routes/services/ev-charger'
import { Route as ServicesEmergencyRouteImport } from './routes/services/emergency'
import { Route as ServicesCommercialHvacRouteImport } from './routes/services/commercial-hvac'
import { Route as ServicesCommercialRouteImport } from './routes/services/commercial'
import { Route as ServicesCctvCameraRouteImport } from './routes/services/cctv-camera'
import { Route as ServicesAirConditioningRouteImport } from './routes/services/air-conditioning'
import { Route as ServicesAcRepairTomballRouteImport } from './routes/services/ac-repair-tomball'
import { Route as ServicesAcRepairCypressRouteImport } from './routes/services/ac-repair-cypress'
import { Route as DashboardLoginRouteImport } from './routes/dashboard/login'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWiringRewiringRoute = ServicesWiringRewiringRouteImport.update({
  id: '/wiring-rewiring',
  path: '/wiring-rewiring',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSecuritySystemsRoute = ServicesSecuritySystemsRouteImport.update({
  id: '/security-systems',
  path: '/security-systems',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesResidentialHvacRoute = ServicesResidentialHvacRouteImport.update({
  id: '/residential-hvac',
  path: '/residential-hvac',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesResidentialRoute = ServicesResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPanelUpgradesRoute = ServicesPanelUpgradesRouteImport.update({
  id: '/panel-upgrades',
  path: '/panel-upgrades',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesIndustrialRoute = ServicesIndustrialRouteImport.update({
  id: '/industrial',
  path: '/industrial',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesIndoorAirQualityRoute =
  ServicesIndoorAirQualityRouteImport.update({
    id: '/indoor-air-quality',
    path: '/indoor-air-quality',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesHvacRepairsRoute = ServicesHvacRepairsRouteImport.update({
  id: '/hvac-repairs',
  path: '/hvac-repairs',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHvacMaintenanceRoute = ServicesHvacMaintenanceRouteImport.update({
  id: '/hvac-maintenance',
  path: '/hvac-maintenance',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHvacInstallRoute = ServicesHvacInstallRouteImport.update({
  id: '/hvac-install',
  path: '/hvac-install',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHeatingRoute = ServicesHeatingRouteImport.update({
  id: '/heating',
  path: '/heating',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGeneratorRoute = ServicesGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEvChargerRoute = ServicesEvChargerRouteImport.update({
  id: '/ev-charger',
  path: '/ev-charger',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEmergencyRoute = ServicesEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCommercialHvacRoute = ServicesCommercialHvacRouteImport.update({
  id: '/commercial-hvac',
  path: '/commercial-hvac',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCommercialRoute = ServicesCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCctvCameraRoute = ServicesCctvCameraRouteImport.update({
  id: '/cctv-camera',
  path: '/cctv-camera',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAirConditioningRoute = ServicesAirConditioningRouteImport.update({
  id: '/air-conditioning',
  path: '/air-conditioning',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAcRepairTomballRoute = ServicesAcRepairTomballRouteImport.update({
  id: '/ac-repair-tomball',
  path: '/ac-repair-tomball',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAcRepairCypressRoute = ServicesAcRepairCypressRouteImport.update({
  id: '/ac-repair-cypress',
  path: '/ac-repair-cypress',
  getParentRoute: () => ServicesRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/dashboard/login',
  path: '/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/ac-repair-cypress': typeof ServicesAcRepairCypressRoute
  '/services/ac-repair-tomball': typeof ServicesAcRepairTomballRoute
  '/services/air-conditioning': typeof ServicesAirConditioningRoute
  '/services/cctv-camera': typeof ServicesCctvCameraRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/commercial-hvac': typeof ServicesCommercialHvacRoute
  '/services/emergency': typeof ServicesEmergencyRoute
  '/services/ev-charger': typeof ServicesEvChargerRoute
  '/services/generator': typeof ServicesGeneratorRoute
  '/services/heating': typeof ServicesHeatingRoute
  '/services/hvac-install': typeof ServicesHvacInstallRoute
  '/services/hvac-maintenance': typeof ServicesHvacMaintenanceRoute
  '/services/hvac-repairs': typeof ServicesHvacRepairsRoute
  '/services/indoor-air-quality': typeof ServicesIndoorAirQualityRoute
  '/services/industrial': typeof ServicesIndustrialRoute
  '/services/panel-upgrades': typeof ServicesPanelUpgradesRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/residential-hvac': typeof ServicesResidentialHvacRoute
  '/services/security-systems': typeof ServicesSecuritySystemsRoute
  '/services/wiring-rewiring': typeof ServicesWiringRewiringRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/ac-repair-cypress': typeof ServicesAcRepairCypressRoute
  '/services/ac-repair-tomball': typeof ServicesAcRepairTomballRoute
  '/services/air-conditioning': typeof ServicesAirConditioningRoute
  '/services/cctv-camera': typeof ServicesCctvCameraRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/commercial-hvac': typeof ServicesCommercialHvacRoute
  '/services/emergency': typeof ServicesEmergencyRoute
  '/services/ev-charger': typeof ServicesEvChargerRoute
  '/services/generator': typeof ServicesGeneratorRoute
  '/services/heating': typeof ServicesHeatingRoute
  '/services/hvac-install': typeof ServicesHvacInstallRoute
  '/services/hvac-maintenance': typeof ServicesHvacMaintenanceRoute
  '/services/hvac-repairs': typeof ServicesHvacRepairsRoute
  '/services/indoor-air-quality': typeof ServicesIndoorAirQualityRoute
  '/services/industrial': typeof ServicesIndustrialRoute
  '/services/panel-upgrades': typeof ServicesPanelUpgradesRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/residential-hvac': typeof ServicesResidentialHvacRoute
  '/services/security-systems': typeof ServicesSecuritySystemsRoute
  '/services/wiring-rewiring': typeof ServicesWiringRewiringRoute
  '/dashboard': typeof DashboardIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/ac-repair-cypress': typeof ServicesAcRepairCypressRoute
  '/services/ac-repair-tomball': typeof ServicesAcRepairTomballRoute
  '/services/air-conditioning': typeof ServicesAirConditioningRoute
  '/services/cctv-camera': typeof ServicesCctvCameraRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/commercial-hvac': typeof ServicesCommercialHvacRoute
  '/services/emergency': typeof ServicesEmergencyRoute
  '/services/ev-charger': typeof ServicesEvChargerRoute
  '/services/generator': typeof ServicesGeneratorRoute
  '/services/heating': typeof ServicesHeatingRoute
  '/services/hvac-install': typeof ServicesHvacInstallRoute
  '/services/hvac-maintenance': typeof ServicesHvacMaintenanceRoute
  '/services/hvac-repairs': typeof ServicesHvacRepairsRoute
  '/services/indoor-air-quality': typeof ServicesIndoorAirQualityRoute
  '/services/industrial': typeof ServicesIndustrialRoute
  '/services/panel-upgrades': typeof ServicesPanelUpgradesRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/residential-hvac': typeof ServicesResidentialHvacRoute
  '/services/security-systems': typeof ServicesSecuritySystemsRoute
  '/services/wiring-rewiring': typeof ServicesWiringRewiringRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/projects'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/services/ac-repair-cypress'
    | '/services/ac-repair-tomball'
    | '/services/air-conditioning'
    | '/services/cctv-camera'
    | '/services/commercial'
    | '/services/commercial-hvac'
    | '/services/emergency'
    | '/services/ev-charger'
    | '/services/generator'
    | '/services/heating'
    | '/services/hvac-install'
    | '/services/hvac-maintenance'
    | '/services/hvac-repairs'
    | '/services/indoor-air-quality'
    | '/services/industrial'
    | '/services/panel-upgrades'
    | '/services/residential'
    | '/services/residential-hvac'
    | '/services/security-systems'
    | '/services/wiring-rewiring'
    | '/dashboard/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/projects'
    | '/reviews'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/services/ac-repair-cypress'
    | '/services/ac-repair-tomball'
    | '/services/air-conditioning'
    | '/services/cctv-camera'
    | '/services/commercial'
    | '/services/commercial-hvac'
    | '/services/emergency'
    | '/services/ev-charger'
    | '/services/generator'
    | '/services/heating'
    | '/services/hvac-install'
    | '/services/hvac-maintenance'
    | '/services/hvac-repairs'
    | '/services/indoor-air-quality'
    | '/services/industrial'
    | '/services/panel-upgrades'
    | '/services/residential'
    | '/services/residential-hvac'
    | '/services/security-systems'
    | '/services/wiring-rewiring'
    | '/dashboard'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/projects'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/services/ac-repair-cypress'
    | '/services/ac-repair-tomball'
    | '/services/air-conditioning'
    | '/services/cctv-camera'
    | '/services/commercial'
    | '/services/commercial-hvac'
    | '/services/emergency'
    | '/services/ev-charger'
    | '/services/generator'
    | '/services/heating'
    | '/services/hvac-install'
    | '/services/hvac-maintenance'
    | '/services/hvac-repairs'
    | '/services/indoor-air-quality'
    | '/services/industrial'
    | '/services/panel-upgrades'
    | '/services/residential'
    | '/services/residential-hvac'
    | '/services/security-systems'
    | '/services/wiring-rewiring'
    | '/dashboard/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/wiring-rewiring': {
      id: '/services/wiring-rewiring'
      path: '/wiring-rewiring'
      fullPath: '/services/wiring-rewiring'
      preLoaderRoute: typeof ServicesWiringRewiringRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/security-systems': {
      id: '/services/security-systems'
      path: '/security-systems'
      fullPath: '/services/security-systems'
      preLoaderRoute: typeof ServicesSecuritySystemsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/residential-hvac': {
      id: '/services/residential-hvac'
      path: '/residential-hvac'
      fullPath: '/services/residential-hvac'
      preLoaderRoute: typeof ServicesResidentialHvacRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/residential': {
      id: '/services/residential'
      path: '/residential'
      fullPath: '/services/residential'
      preLoaderRoute: typeof ServicesResidentialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/panel-upgrades': {
      id: '/services/panel-upgrades'
      path: '/panel-upgrades'
      fullPath: '/services/panel-upgrades'
      preLoaderRoute: typeof ServicesPanelUpgradesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/industrial': {
      id: '/services/industrial'
      path: '/industrial'
      fullPath: '/services/industrial'
      preLoaderRoute: typeof ServicesIndustrialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/indoor-air-quality': {
      id: '/services/indoor-air-quality'
      path: '/indoor-air-quality'
      fullPath: '/services/indoor-air-quality'
      preLoaderRoute: typeof ServicesIndoorAirQualityRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/hvac-repairs': {
      id: '/services/hvac-repairs'
      path: '/hvac-repairs'
      fullPath: '/services/hvac-repairs'
      preLoaderRoute: typeof ServicesHvacRepairsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/hvac-maintenance': {
      id: '/services/hvac-maintenance'
      path: '/hvac-maintenance'
      fullPath: '/services/hvac-maintenance'
      preLoaderRoute: typeof ServicesHvacMaintenanceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/hvac-install': {
      id: '/services/hvac-install'
      path: '/hvac-install'
      fullPath: '/services/hvac-install'
      preLoaderRoute: typeof ServicesHvacInstallRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/heating': {
      id: '/services/heating'
      path: '/heating'
      fullPath: '/services/heating'
      preLoaderRoute: typeof ServicesHeatingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/generator': {
      id: '/services/generator'
      path: '/generator'
      fullPath: '/services/generator'
      preLoaderRoute: typeof ServicesGeneratorRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ev-charger': {
      id: '/services/ev-charger'
      path: '/ev-charger'
      fullPath: '/services/ev-charger'
      preLoaderRoute: typeof ServicesEvChargerRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/emergency': {
      id: '/services/emergency'
      path: '/emergency'
      fullPath: '/services/emergency'
      preLoaderRoute: typeof ServicesEmergencyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/commercial-hvac': {
      id: '/services/commercial-hvac'
      path: '/commercial-hvac'
      fullPath: '/services/commercial-hvac'
      preLoaderRoute: typeof ServicesCommercialHvacRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/commercial': {
      id: '/services/commercial'
      path: '/commercial'
      fullPath: '/services/commercial'
      preLoaderRoute: typeof ServicesCommercialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cctv-camera': {
      id: '/services/cctv-camera'
      path: '/cctv-camera'
      fullPath: '/services/cctv-camera'
      preLoaderRoute: typeof ServicesCctvCameraRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/air-conditioning': {
      id: '/services/air-conditioning'
      path: '/air-conditioning'
      fullPath: '/services/air-conditioning'
      preLoaderRoute: typeof ServicesAirConditioningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ac-repair-tomball': {
      id: '/services/ac-repair-tomball'
      path: '/ac-repair-tomball'
      fullPath: '/services/ac-repair-tomball'
      preLoaderRoute: typeof ServicesAcRepairTomballRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ac-repair-cypress': {
      id: '/services/ac-repair-cypress'
      path: '/ac-repair-cypress'
      fullPath: '/services/ac-repair-cypress'
      preLoaderRoute: typeof ServicesAcRepairCypressRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/dashboard/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesAcRepairCypressRoute: typeof ServicesAcRepairCypressRoute
  ServicesAcRepairTomballRoute: typeof ServicesAcRepairTomballRoute
  ServicesAirConditioningRoute: typeof ServicesAirConditioningRoute
  ServicesCctvCameraRoute: typeof ServicesCctvCameraRoute
  ServicesCommercialRoute: typeof ServicesCommercialRoute
  ServicesCommercialHvacRoute: typeof ServicesCommercialHvacRoute
  ServicesEmergencyRoute: typeof ServicesEmergencyRoute
  ServicesEvChargerRoute: typeof ServicesEvChargerRoute
  ServicesGeneratorRoute: typeof ServicesGeneratorRoute
  ServicesHeatingRoute: typeof ServicesHeatingRoute
  ServicesHvacInstallRoute: typeof ServicesHvacInstallRoute
  ServicesHvacMaintenanceRoute: typeof ServicesHvacMaintenanceRoute
  ServicesHvacRepairsRoute: typeof ServicesHvacRepairsRoute
  ServicesIndoorAirQualityRoute: typeof ServicesIndoorAirQualityRoute
  ServicesIndustrialRoute: typeof ServicesIndustrialRoute
  ServicesPanelUpgradesRoute: typeof ServicesPanelUpgradesRoute
  ServicesResidentialRoute: typeof ServicesResidentialRoute
  ServicesResidentialHvacRoute: typeof ServicesResidentialHvacRoute
  ServicesSecuritySystemsRoute: typeof ServicesSecuritySystemsRoute
  ServicesWiringRewiringRoute: typeof ServicesWiringRewiringRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAcRepairCypressRoute: ServicesAcRepairCypressRoute,
  ServicesAcRepairTomballRoute: ServicesAcRepairTomballRoute,
  ServicesAirConditioningRoute: ServicesAirConditioningRoute,
  ServicesCctvCameraRoute: ServicesCctvCameraRoute,
  ServicesCommercialRoute: ServicesCommercialRoute,
  ServicesCommercialHvacRoute: ServicesCommercialHvacRoute,
  ServicesEmergencyRoute: ServicesEmergencyRoute,
  ServicesEvChargerRoute: ServicesEvChargerRoute,
  ServicesGeneratorRoute: ServicesGeneratorRoute,
  ServicesHeatingRoute: ServicesHeatingRoute,
  ServicesHvacInstallRoute: ServicesHvacInstallRoute,
  ServicesHvacMaintenanceRoute: ServicesHvacMaintenanceRoute,
  ServicesHvacRepairsRoute: ServicesHvacRepairsRoute,
  ServicesIndoorAirQualityRoute: ServicesIndoorAirQualityRoute,
  ServicesIndustrialRoute: ServicesIndustrialRoute,
  ServicesPanelUpgradesRoute: ServicesPanelUpgradesRoute,
  ServicesResidentialRoute: ServicesResidentialRoute,
  ServicesResidentialHvacRoute: ServicesResidentialHvacRoute,
  ServicesSecuritySystemsRoute: ServicesSecuritySystemsRoute,
  ServicesWiringRewiringRoute: ServicesWiringRewiringRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
