/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpfrontPricingRouteImport } from './routes/upfront-pricing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RequestFreeEstimateRouteImport } from './routes/request-free-estimate'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutOwnerRouteImport } from './routes/about-owner'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ServicesResidentialHvacRouteImport } from './routes/services/residential-hvac'
import { Route as ServicesIndoorAirQualityRouteImport } from './routes/services/indoor-air-quality'
import { Route as ServicesHvacRepairsRouteImport } from './routes/services/hvac-repairs'
import { Route as ServicesHvacMaintenanceRouteImport } from './routes/services/hvac-maintenance'
import { Route as ServicesHvacInstallRouteImport } from './routes/services/hvac-install'
import { Route as ServicesHeatingRouteImport } from './routes/services/heating'
import { Route as ServicesCommercialHvacRouteImport } from './routes/services/commercial-hvac'
import { Route as ServicesAirConditioningRouteImport } from './routes/services/air-conditioning'
import { Route as ServicesAcRepairTomballRouteImport } from './routes/services/ac-repair-tomball'
import { Route as ServicesAcRepairCypressRouteImport } from './routes/services/ac-repair-cypress'
import { Route as DashboardLoginRouteImport } from './routes/dashboard/login'

const UpfrontPricingRoute = UpfrontPricingRouteImport.update({
  id: '/upfront-pricing',
  path: '/upfront-pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestFreeEstimateRoute = RequestFreeEstimateRouteImport.update({
  id: '/request-free-estimate',
  path: '/request-free-estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOwnerRoute = AboutOwnerRouteImport.update({
  id: '/about-owner',
  path: '/about-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesResidentialHvacRoute = ServicesResidentialHvacRouteImport.update({
  id: '/residential-hvac',
  path: '/residential-hvac',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesIndoorAirQualityRoute =
  ServicesIndoorAirQualityRouteImport.update({
    id: '/indoor-air-quality',
    path: '/indoor-air-quality',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesHvacRepairsRoute = ServicesHvacRepairsRouteImport.update({
  id: '/hvac-repairs',
  path: '/hvac-repairs',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHvacMaintenanceRoute = ServicesHvacMaintenanceRouteImport.update({
  id: '/hvac-maintenance',
  path: '/hvac-maintenance',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHvacInstallRoute = ServicesHvacInstallRouteImport.update({
  id: '/hvac-install',
  path: '/hvac-install',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHeatingRoute = ServicesHeatingRouteImport.update({
  id: '/heating',
  path: '/heating',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCommercialHvacRoute = ServicesCommercialHvacRouteImport.update({
  id: '/commercial-hvac',
  path: '/commercial-hvac',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAirConditioningRoute = ServicesAirConditioningRouteImport.update({
  id: '/air-conditioning',
  path: '/air-conditioning',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAcRepairTomballRoute = ServicesAcRepairTomballRouteImport.update({
  id: '/ac-repair-tomball',
  path: '/ac-repair-tomball',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAcRepairCypressRoute = ServicesAcRepairCypressRouteImport.update({
  id: '/ac-repair-cypress',
  path: '/ac-repair-cypress',
  getParentRoute: () => ServicesRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/dashboard/login',
  path: '/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-owner': typeof AboutOwnerRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/projects': typeof ProjectsRoute
  '/request-free-estimate': typeof RequestFreeEstimateRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upfront-pricing': typeof UpfrontPricingRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/ac-repair-cypress': typeof ServicesAcRepairCypressRoute
  '/services/ac-repair-tomball': typeof ServicesAcRepairTomballRoute
  '/services/air-conditioning': typeof ServicesAirConditioningRoute
  '/services/commercial-hvac': typeof ServicesCommercialHvacRoute
  '/services/heating': typeof ServicesHeatingRoute
  '/services/hvac-install': typeof ServicesHvacInstallRoute
  '/services/hvac-maintenance': typeof ServicesHvacMaintenanceRoute
  '/services/hvac-repairs': typeof ServicesHvacRepairsRoute
  '/services/indoor-air-quality': typeof ServicesIndoorAirQualityRoute
  '/services/residential-hvac': typeof ServicesResidentialHvacRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-owner': typeof AboutOwnerRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/projects': typeof ProjectsRoute
  '/request-free-estimate': typeof RequestFreeEstimateRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upfront-pricing': typeof UpfrontPricingRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/ac-repair-cypress': typeof ServicesAcRepairCypressRoute
  '/services/ac-repair-tomball': typeof ServicesAcRepairTomballRoute
  '/services/air-conditioning': typeof ServicesAirConditioningRoute
  '/services/commercial-hvac': typeof ServicesCommercialHvacRoute
  '/services/heating': typeof ServicesHeatingRoute
  '/services/hvac-install': typeof ServicesHvacInstallRoute
  '/services/hvac-maintenance': typeof ServicesHvacMaintenanceRoute
  '/services/hvac-repairs': typeof ServicesHvacRepairsRoute
  '/services/indoor-air-quality': typeof ServicesIndoorAirQualityRoute
  '/services/residential-hvac': typeof ServicesResidentialHvacRoute
  '/dashboard': typeof DashboardIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-owner': typeof AboutOwnerRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/projects': typeof ProjectsRoute
  '/request-free-estimate': typeof RequestFreeEstimateRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upfront-pricing': typeof UpfrontPricingRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/ac-repair-cypress': typeof ServicesAcRepairCypressRoute
  '/services/ac-repair-tomball': typeof ServicesAcRepairTomballRoute
  '/services/air-conditioning': typeof ServicesAirConditioningRoute
  '/services/commercial-hvac': typeof ServicesCommercialHvacRoute
  '/services/heating': typeof ServicesHeatingRoute
  '/services/hvac-install': typeof ServicesHvacInstallRoute
  '/services/hvac-maintenance': typeof ServicesHvacMaintenanceRoute
  '/services/hvac-repairs': typeof ServicesHvacRepairsRoute
  '/services/indoor-air-quality': typeof ServicesIndoorAirQualityRoute
  '/services/residential-hvac': typeof ServicesResidentialHvacRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-owner'
    | '/careers'
    | '/contact'
    | '/finance'
    | '/projects'
    | '/request-free-estimate'
    | '/reviews'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/upfront-pricing'
    | '/dashboard/login'
    | '/services/ac-repair-cypress'
    | '/services/ac-repair-tomball'
    | '/services/air-conditioning'
    | '/services/commercial-hvac'
    | '/services/heating'
    | '/services/hvac-install'
    | '/services/hvac-maintenance'
    | '/services/hvac-repairs'
    | '/services/indoor-air-quality'
    | '/services/residential-hvac'
    | '/dashboard/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-owner'
    | '/careers'
    | '/contact'
    | '/finance'
    | '/projects'
    | '/request-free-estimate'
    | '/reviews'
    | '/service-areas'
    | '/sitemap.xml'
    | '/upfront-pricing'
    | '/dashboard/login'
    | '/services/ac-repair-cypress'
    | '/services/ac-repair-tomball'
    | '/services/air-conditioning'
    | '/services/commercial-hvac'
    | '/services/heating'
    | '/services/hvac-install'
    | '/services/hvac-maintenance'
    | '/services/hvac-repairs'
    | '/services/indoor-air-quality'
    | '/services/residential-hvac'
    | '/dashboard'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-owner'
    | '/careers'
    | '/contact'
    | '/finance'
    | '/projects'
    | '/request-free-estimate'
    | '/reviews'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/upfront-pricing'
    | '/dashboard/login'
    | '/services/ac-repair-cypress'
    | '/services/ac-repair-tomball'
    | '/services/air-conditioning'
    | '/services/commercial-hvac'
    | '/services/heating'
    | '/services/hvac-install'
    | '/services/hvac-maintenance'
    | '/services/hvac-repairs'
    | '/services/indoor-air-quality'
    | '/services/residential-hvac'
    | '/dashboard/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutOwnerRoute: typeof AboutOwnerRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FinanceRoute: typeof FinanceRoute
  ProjectsRoute: typeof ProjectsRoute
  RequestFreeEstimateRoute: typeof RequestFreeEstimateRoute
  ReviewsRoute: typeof ReviewsRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UpfrontPricingRoute: typeof UpfrontPricingRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upfront-pricing': {
      id: '/upfront-pricing'
      path: '/upfront-pricing'
      fullPath: '/upfront-pricing'
      preLoaderRoute: typeof UpfrontPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-free-estimate': {
      id: '/request-free-estimate'
      path: '/request-free-estimate'
      fullPath: '/request-free-estimate'
      preLoaderRoute: typeof RequestFreeEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-owner': {
      id: '/about-owner'
      path: '/about-owner'
      fullPath: '/about-owner'
      preLoaderRoute: typeof AboutOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/residential-hvac': {
      id: '/services/residential-hvac'
      path: '/residential-hvac'
      fullPath: '/services/residential-hvac'
      preLoaderRoute: typeof ServicesResidentialHvacRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/indoor-air-quality': {
      id: '/services/indoor-air-quality'
      path: '/indoor-air-quality'
      fullPath: '/services/indoor-air-quality'
      preLoaderRoute: typeof ServicesIndoorAirQualityRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/hvac-repairs': {
      id: '/services/hvac-repairs'
      path: '/hvac-repairs'
      fullPath: '/services/hvac-repairs'
      preLoaderRoute: typeof ServicesHvacRepairsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/hvac-maintenance': {
      id: '/services/hvac-maintenance'
      path: '/hvac-maintenance'
      fullPath: '/services/hvac-maintenance'
      preLoaderRoute: typeof ServicesHvacMaintenanceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/hvac-install': {
      id: '/services/hvac-install'
      path: '/hvac-install'
      fullPath: '/services/hvac-install'
      preLoaderRoute: typeof ServicesHvacInstallRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/heating': {
      id: '/services/heating'
      path: '/heating'
      fullPath: '/services/heating'
      preLoaderRoute: typeof ServicesHeatingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/commercial-hvac': {
      id: '/services/commercial-hvac'
      path: '/commercial-hvac'
      fullPath: '/services/commercial-hvac'
      preLoaderRoute: typeof ServicesCommercialHvacRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/air-conditioning': {
      id: '/services/air-conditioning'
      path: '/air-conditioning'
      fullPath: '/services/air-conditioning'
      preLoaderRoute: typeof ServicesAirConditioningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ac-repair-tomball': {
      id: '/services/ac-repair-tomball'
      path: '/ac-repair-tomball'
      fullPath: '/services/ac-repair-tomball'
      preLoaderRoute: typeof ServicesAcRepairTomballRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ac-repair-cypress': {
      id: '/services/ac-repair-cypress'
      path: '/ac-repair-cypress'
      fullPath: '/services/ac-repair-cypress'
      preLoaderRoute: typeof ServicesAcRepairCypressRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/dashboard/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesAcRepairCypressRoute: typeof ServicesAcRepairCypressRoute
  ServicesAcRepairTomballRoute: typeof ServicesAcRepairTomballRoute
  ServicesAirConditioningRoute: typeof ServicesAirConditioningRoute
  ServicesCommercialHvacRoute: typeof ServicesCommercialHvacRoute
  ServicesHeatingRoute: typeof ServicesHeatingRoute
  ServicesHvacInstallRoute: typeof ServicesHvacInstallRoute
  ServicesHvacMaintenanceRoute: typeof ServicesHvacMaintenanceRoute
  ServicesHvacRepairsRoute: typeof ServicesHvacRepairsRoute
  ServicesIndoorAirQualityRoute: typeof ServicesIndoorAirQualityRoute
  ServicesResidentialHvacRoute: typeof ServicesResidentialHvacRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAcRepairCypressRoute: ServicesAcRepairCypressRoute,
  ServicesAcRepairTomballRoute: ServicesAcRepairTomballRoute,
  ServicesAirConditioningRoute: ServicesAirConditioningRoute,
  ServicesCommercialHvacRoute: ServicesCommercialHvacRoute,
  ServicesHeatingRoute: ServicesHeatingRoute,
  ServicesHvacInstallRoute: ServicesHvacInstallRoute,
  ServicesHvacMaintenanceRoute: ServicesHvacMaintenanceRoute,
  ServicesHvacRepairsRoute: ServicesHvacRepairsRoute,
  ServicesIndoorAirQualityRoute: ServicesIndoorAirQualityRoute,
  ServicesResidentialHvacRoute: ServicesResidentialHvacRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutOwnerRoute: AboutOwnerRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FinanceRoute: FinanceRoute,
  ProjectsRoute: ProjectsRoute,
  RequestFreeEstimateRoute: RequestFreeEstimateRoute,
  ReviewsRoute: ReviewsRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UpfrontPricingRoute: UpfrontPricingRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
